version: '3.3'
services:
    mysql:
        restart: always
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=@1Nfr4struktur
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - '/var/run/mysqld/:/var/run/mysqld/'
            - '/opt/MYSQL_DATA:/var/lib/mysql'
        image: mysql
        networks:
            - development
    phpmyadmin:
        restart: always
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - '7000:80'
        image: phpmyadmin
        networks:
            - development

networks:
  development:
    name: development
    driver: bridge
